package kernitus.plugin.Hotels;

public enum HotelsResult {
SIGN_FILE_NON_EXISTENT, HOTEL_NON_EXISTENT, ROOM_NON_EXISTENT, FILE_NON_EXISTENT, WORLD_NON_EXISTENT, USER_NON_EXISTENT, 
 BLOCK_NOT_SIGN, OUT_OF_REGION, SUCCESS, NO_RENTER, NEW_NUM_TOO_BIG, IS_RENTED, IS_NOT_RENTED, FRIEND_NOT_IN_LIST
}
